### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Llombe** [BongoHive/internship-program#13]
For the front end assignment are the two introduction to HTML bulletins optional or its just the one in the first bulletin?

<img width="967" alt="Screenshot 2019-06-08 at 05 35 57" src="https://user-images.githubusercontent.com/42071604/59142052-d8238780-89af-11e9-98d9-3cd7b1f8229b.png">

**Comment by Joebbrien** [comment]
The one with the optional tag is the optional one
