### ISSUE TITLE
Backend rest-api-express-postman Assignment

### ISSUE THREAD

**Issue by dtembo98** [BongoHive/internship-program#15]
The instructions are not clear as to what is suppose to be done for the delete endpoints API routes.
are we suppose to delete the province or country  specified in the url ? or just delete the recently added province or country ?

**Comment by OlivierJM** [comment]
@joebbrien ☝🏿☝🏿☝🏿

**Comment by Joebbrien** [comment]
Hi @blackhat198 thanks for raising an issue.

You will have to delete the sent data(country or province) which will be in the url from data structures (provinces or countries)

Thanks

**Comment by dtembo98** [comment]
Thank you
