### ISSUE TITLE
Failure to setup Assignment repo

### ISSUE THREAD

**Issue by Wamundila** [BongoHive/internship-program#17]
**Is this question about the internship?**
Yes

**Add a link here to repository with the problem**
[css introduction] (https://classroom.github.com/a/V-0w1V1Y)

**Describe your question**
Failing to create repository.
![error](https://user-images.githubusercontent.com/51416674/59203704-6ca00c80-8b9f-11e9-8bfa-f44528c9e389.JPG)

**Comment by alfeyo** [comment]
Hello, @Wamundila we are looking into your query. We will notify you as soon as it is resolved.

**Comment by japhetmesa** [comment]
Have same issue.

**Comment by Wamundila** [comment]
Hello @alfeyo , any update.

**Comment by alfeyo** [comment]
Thank you for getting in touch. We are currently experiencing an issue on the platform and will get back to you as soon as it's sorted out.

**Comment by Mulubwa17** [comment]
same problem

**Comment by alfeyo** [comment]
Thank you @Mulubwa17  for getting in touch. We are currently experiencing an issue on the platform and will get back to you as soon as it's sorted out.

**Comment by japhetmesa** [comment]
I think I am finally in. :)

Best regards,

*Japhet Kapambwe Mesa*
*+260974232610 / +260964393112*

**Comment by Wamundila** [comment]
I have also managed. @Mulubwa17 , please comment if youve also managed.

**Comment by Mulubwa17** [comment]
got in too

**Comment by Wamundila** [comment]
@Mulubwa17 , thanks, Closing the issue now.
