### ISSUE TITLE
question

### ISSUE THREAD

**Issue by makilimusepa** [BongoHive/internship-program#18]
**Is this question about the internship?**
Yes

**Add a link here to repository with the problem**
css-introduction

**Describe your question**
I need some clarification on the workflow. So do I just clone the repo to my local machine, then do my work, make commits and push it all back to the master branch on GitHub?

**Comment by alfeyo** [comment]
Hello, @mcdee92 Yes that's right, doing the following will allow us to view your changes.

- kindly close this issue if you feel your question has been answered.
Thank you

**Comment by OlivierJM** [comment]
As Alfeyo has said, you are free to make changes either on your local machine or in the Github editor, just make sure you commit and your changes are reflecting.

**Comment by makilimusepa** [comment]
Alright. Thanks.
