### ISSUE TITLE
Assignment repository Error message

### ISSUE THREAD

**Issue by ckabali** [BongoHive/internship-program#20]
![Screenshot_2019-06-11-07-04-38](https://user-images.githubusercontent.com/51477747/59245388-dc9ea900-8c18-11e9-8e48-4e50e553c011.png)

**Comment by smaboshe** [comment]
Hello, @ckabali!

Thanks for letting us know. We are looking into this and hope to have it resolved soon.

**Comment by ckabali** [comment]
Depending on how long it will take you to fix the problem is the extension which am asking you to generously give us.

**Comment by Beardless-sheik** [comment]
Hi,

Same issue too!!
![error](https://user-images.githubusercontent.com/44676055/59349632-6c784c00-8d1a-11e9-8818-8b8052221aa3.JPG)

**Comment by alfeyo** [comment]
Thank you for getting in touch. We are currently experiencing an issue on the platform and will get back to you as soon as it's sorted out.

**Comment by ckabali** [comment]
Thanks sir

**Comment by ckabali** [comment]
You welcome
