### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Wyttee** [BongoHive/internship-program#22]
**Is this question about the internship?**
Yes 

**Add a link here to repository with the problem**
[CSS first assignment](https://classroom.github.com/assignment-invitations/7714701e71d596723774de00f278d345/setup).
**Describe your question**
Its failing to create a repository for me. I wanted to ask if the opportunity is still available.

![Screenshot (91)](https://user-images.githubusercontent.com/27861429/59291649-aba39000-8c7b-11e9-9ca3-0731d05c84cd.png)

**Comment by Wyttee** [comment]
I still have the same issue even today any help please.?

**Comment by alfeyo** [comment]
Thank you @Wyttee for getting in touch. We are currently experiencing an issue on the platform and will get back to you as soon as it's sorted out.

**Comment by Wyttee** [comment]
@alfeyo I'm just from trying it and it's still giving me the same issue.

**Comment by Wyttee** [comment]
Its working fine now. Thank you.
