### ISSUE TITLE
Progress No. 11 failing to merge

### ISSUE THREAD

**Issue by blessedjasonmwanza** [BongoHive/internship-program#24]
Under fundamentals (Introduction to HTML), a second assignment which is guided by a github bot (@beardofedu) , i was requested to add a stylesheet and merge to add-style branch. though i did the above requested, i'm still failing to merge. The status says -> 1 or more reviewers are required to review my pull request.

**Comment by beardofedu** [comment]
Hey @blessedjasonmwanza , I'm not a bot, but I helped work on the Introduction to HTML course. What is happening in the course that is preventing you from completing the class?

**Comment by blessedjasonmwanza** [comment]
I just needed a collaborator to merge the code.. done. Thanks a lot @beardofedu
