### ISSUE TITLE
failing to create repository for the assignment

### ISSUE THREAD

**Issue by Big-Zude** [BongoHive/internship-program#3]
After accepting the assignment [here](https://classroom.github.com/assignment-invitations/7714701e71d596723774de00f278d345/setup) for CSS Introduction
Am faced with this problem: _**We were not able to import you the starter code to your assignment, please try again.**_ 
I need assistance with that.

![Screenshot](https://user-images.githubusercontent.com/40924941/58747511-5f32a600-846c-11e9-9f0a-58686e8b200d.png)

**Comment by OlivierJM** [comment]
This is not public yet so we will get back to you on Monday.

**Comment by Big-Zude** [comment]
Alright

**Comment by OlivierJM** [comment]
Hi Zude, have you tried again ?

**Comment by Big-Zude** [comment]
i just tried it now and still the same result

**Comment by OlivierJM** [comment]
You are still getting the same red screen ? 
Don’t cancel the process but click on the try again button and give it time?

**Comment by OlivierJM** [comment]
Alternatively You can check other assignments you can start meantime.

**Comment by Big-Zude** [comment]
> You are still getting the same red screen ?
> Don’t cancel the process but click on the try again button and give it time?

yes am getting the same screen and i keep clicking the retry button

**Comment by Big-Zude** [comment]
> Alternatively You can check other assignments you can start meantime.

alright

**Comment by OlivierJM** [comment]
Sorry about that, give it time, we will check it.

**Comment by OlivierJM** [comment]
@Big-Zude I can confirm that the css-introduction is working as expected. confirm for me as well so that I can close this issue.

**Comment by Big-Zude** [comment]
yes, importing the starter code now.

**Comment by OlivierJM** [comment]
Awesome, I am closing the issue now. feel free to reopen it where you have a problem again.

**Comment by Nchimzy708** [comment]
i have the same problem

**Comment by OlivierJM** [comment]
> i have the same problem

Noted

**Comment by likezo** [comment]
it failing to create repository for the assignment  i have tried many times
