### ISSUE TITLE
Unable to to take part in the introduction to github learning

### ISSUE THREAD

**Issue by DalitsoKasonde** [BongoHive/internship-program#4]
![Screenshot from 2019-06-04 09-48-12](https://user-images.githubusercontent.com/42833473/58861275-4f0a0900-86ae-11e9-95b0-10c2f382c01a.png)
As the web pages asks that i  install the app
Please not that though i have vscode and git install my machine runs on linux

**Comment by OlivierJM** [comment]
Hi Dalitso,
This has nothing to do with your local installation, it’s the GitHub training app that you need to install on your GitHub repo. 
Click the provided link where it’s says install app and follow instructions.

**Comment by DalitsoKasonde** [comment]
thank you Olivier
it worked

**Comment by OlivierJM** [comment]
I am glad to hear it helped.
