### ISSUE TITLE
Having this issue, Is it Comming from my account or Bongo Hive?

### ISSUE THREAD

**Issue by sokogfb** [BongoHive/internship-program#5]
**Is this question about the internship?**
Yes
**Description of my problem**
Hello Team, Am facing this cahllenge When trying to proceed to CSS Assignment 2.  
![Capture Issue](https://user-images.githubusercontent.com/32112696/59034351-28450180-886b-11e9-9991-250c8d1d4307.PNG)

**Comment by OlivierJM** [comment]
We are looking into this and we will notify you as soon as it is fixed.

**Comment by OlivierJM** [comment]
[UPDATE]
This is not your issue and it is from the Github side and it will be resolved soon and this related to this #6

**Comment by Nchimzy708** [comment]
oh okay...but can the questions be uploaded as readme..so that we clone and submit just for now Sir

**Comment by Joebbrien** [comment]
Hi @SOXCODE Thanks for raising this issue.

We have worked on this and you should be able to access the assignments now.

Try accessing the assignments and let us know if you have any problems

Thanks
