### ISSUE TITLE
Failing to Accept Assignments

### ISSUE THREAD

**Issue by Nchimzy708** [BongoHive/internship-program#6]
am failing to accept the assignments it  keeps saying try again and brings errored..can i please get some assistance or an invite to the assignments

**Comment by OlivierJM** [comment]
Hi @Nchimzy708 sorry about that, 
We know the issue and it is currently being worked on

**Comment by typeXx** [comment]
Same here

**Comment by Joebbrien** [comment]
Hi all, thanks for raising this issue. We have been working on this and seems like it has been resolved. 
You can go ahead and should be able to access the assignments with easy now.

Let us know if you have any difficulties.

Thanks

**Comment by soulmonger** [comment]
Hello, I'm facing the same challenge. I can not access any assignment even though I have a repository and an organization and everything.
![error](https://user-images.githubusercontent.com/51358145/59063685-f0f54580-88a8-11e9-8bc4-c9b8aedfacac.PNG)
