### ISSUE TITLE
Why Im i failing to load the assignment still

### ISSUE THREAD

**Issue by soulmonger** [BongoHive/internship-program#7]
Im failing to load the assignment even though i have created a repository and have an organization

![error](https://user-images.githubusercontent.com/51358145/59063986-8f81a680-88a9-11e9-88eb-7d9e6324268b.PNG)

**Comment by OlivierJM** [comment]
Hi 👋 
Have you tried again ? Which assignment were you trying to do?

**Comment by musoleio** [comment]
Hi 
I am facing the same challenge
![Uploading Screenshot from 2019-06-07 08-01-00.png…]()

**Comment by OlivierJM** [comment]
Hi @Musole-Yamboto what assignments was this ?

**Comment by musoleio** [comment]
@OlivierJM that's CSS Introduction

**Comment by OlivierJM** [comment]
@alfeyo @Joebbrien kindly take a look at the above, the sooner you can the better.

**Comment by ghost** [comment]
same here .. kindly help us

**Comment by musoleio** [comment]
@OlivierJM thanks... The challenge has been resolved for me

**Comment by OlivierJM** [comment]
> same here .. kindly help us

@smushibi are you still having the issue? please confirm with me and kindly indicate which assignment it is deriving from. Thank you

**Comment by ghost** [comment]
@OlivierJM  Thank you .. its working now, am glad to be learning something New each day .

**Comment by OlivierJM** [comment]
Awesome, am glad to hear that.. 💪🏾🚀

**Comment by soulmonger** [comment]
Hi..
I have managed to open the assignments for css and javaScript. thank you
