### ISSUE TITLE
How do I know If I completed the application for the program

### ISSUE THREAD

**Issue by DexterKatongo** [BongoHive/internship-program#9]
How do I know that I have completed the application for this programme? before the 14th June as the deadline date

**Comment by OlivierJM** [comment]
Hi @DexterKatongo 
There are 2 tracks of this internship program:
- Front-end(Do all CSS, Javascript and react assignments)
- Back-end (Do all assignments indicated in this section)

Feel free to choose which one you are more comfortable with

**Comment by NicholasMiselo** [comment]
Does this mean if we select a track we have fully applied for the internship program?

**Comment by OlivierJM** [comment]
Not if you just select a track but if you do many assignments in that track then you will highly be considered
